defmodule AshUI.Data do
  @moduledoc """
  Thin CRUD helpers that route Ash operations through `AshUI.Domain`.

  This keeps convenience data access separate from the domain definition itself,
  which avoids conflicts with functions generated by `use Ash.Domain`.
  """

  require Ash.Query

  alias AshUI.Domain

  @doc """
  Creates a record through `AshUI.Domain`, accepting either standard Ash options
  or an `:attrs` key with the input attributes.
  """
  def create(resource, opts \\ []) when is_atom(resource) and is_list(opts) do
    case Keyword.fetch(opts, :attrs) do
      {:ok, attrs} ->
        opts = opts |> Keyword.delete(:attrs) |> Keyword.put(:domain, Domain)
        Ash.create(resource, attrs, opts)

      :error ->
        Ash.create(resource, Keyword.put(opts, :domain, Domain))
    end
  end

  @doc """
  Updates a record through `AshUI.Domain`, accepting either standard Ash options
  or an `:attrs` key with the update attributes.
  """
  def update(record, opts \\ []) when is_list(opts) do
    case Keyword.fetch(opts, :attrs) do
      {:ok, attrs} ->
        opts = opts |> Keyword.delete(:attrs) |> Keyword.put(:domain, Domain)
        Ash.update(record, attrs, opts)

      :error ->
        Ash.update(record, Keyword.put(opts, :domain, Domain))
    end
  end

  @doc """
  Destroys a record through `AshUI.Domain`.
  """
  def destroy(record, opts \\ []) when is_list(opts) do
    Ash.destroy(record, Keyword.put(opts, :domain, Domain))
  end

  @doc """
  Reads a collection of records from the given resource, optionally applying a
  simple keyword filter before delegating to `Ash.read/2`.
  """
  def read(resource, opts \\ []) when is_atom(resource) and is_list(opts) do
    {filter, opts} = Keyword.pop(opts, :filter)
    query = apply_filter(resource, filter)

    Ash.read(query, Keyword.put(opts, :domain, Domain))
  end

  @doc """
  Reads a collection of records and raises on failure.
  """
  def read!(resource, opts \\ []) when is_atom(resource) and is_list(opts) do
    {filter, opts} = Keyword.pop(opts, :filter)
    query = apply_filter(resource, filter)

    Ash.read!(query, Keyword.put(opts, :domain, Domain))
  end

  @doc """
  Reads a single record from the given resource, optionally applying a filter.
  """
  def read_one(resource, opts \\ []) when is_atom(resource) and is_list(opts) do
    {filter, opts} = Keyword.pop(opts, :filter)
    query = apply_filter(resource, filter)

    Ash.read_one(query, Keyword.put(opts, :domain, Domain))
  end

  @doc """
  Reads a single record and raises on failure.
  """
  def read_one!(resource, opts \\ []) when is_atom(resource) and is_list(opts) do
    {filter, opts} = Keyword.pop(opts, :filter)
    query = apply_filter(resource, filter)

    Ash.read_one!(query, Keyword.put(opts, :domain, Domain))
  end

  defp apply_filter(resource, nil), do: resource

  defp apply_filter(resource, filter) do
    resource
    |> Ash.Query.new()
    |> Ash.Query.filter(^filter)
  end
end
