defmodule AshUI.Rendering.WebUIAdapter do
  @moduledoc """
  Adapter for WebUI renderer package.

  This module provides integration with the web_ui package for rendering
  to static HTML with Elm client integration. When the web_ui package is
  not available, this module provides stub implementations.

  If WebUI.Renderer is available, delegates to it. Otherwise, provides
  fallback implementation using the IURAdapter.
  """

  alias AshUI.Rendering.IURAdapter
  alias AshUI.Compilation.IUR

  @doc """
  Renders a canonical IUR to static HTML string.

  ## Parameters
    * `canonical_iur` - Canonical IUR map from IURAdapter
    * `opts` - Rendering options

  ## Options
    * `:seo_enabled` - Include SEO meta tags (default: true)
    * `:elm_enabled` - Enable Elm client integration (default: false)
    * `:elm_module` - Elm module name (default: "Main")
    * `:assets_url` - Base URL for static assets (default: "/assets")

  ## Returns
    * `{:ok, html_string}` - Static HTML string
    * `{:error, reason}` - Rendering failed
  """
  @spec render(map(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def render(canonical_iur, opts \\ []) when is_map(canonical_iur) do
    if Code.ensure_loaded?(WebUI.Renderer) do
      call_web_ui_renderer(canonical_iur, opts)
    else
      render_fallback(canonical_iur, opts)
    end
  end

  @doc """
  Checks if WebUI renderer is available.

  ## Returns
    * `true` - WebUI.Renderer is available
    * `false` - WebUI.Renderer is not available
  """
  @spec available?() :: boolean()
  def available? do
    Code.ensure_loaded?(WebUI.Renderer)
  end

  @doc """
  Converts an Ash IUR to WebUI-compatible format and renders.

  ## Parameters
    * `ash_iur` - Ash IUR structure
    * `opts` - Rendering options

  ## Returns
    * `{:ok, html_string}` - Static HTML string
    * `{:error, reason}` - Rendering failed
  """
  @spec render_ash_iur(IUR.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def render_ash_iur(%IUR{} = ash_iur, opts \\ []) do
    with {:ok, canonical_iur} <- IURAdapter.to_canonical(ash_iur, opts),
         {:ok, html} <- render(canonical_iur, opts) do
      {:ok, html}
    else
      error -> error
    end
  end

  # Private Functions

  # Call actual WebUI.Renderer if available
  defp call_web_ui_renderer(canonical_iur, opts) do
    try do
      case WebUI.Renderer.render(canonical_iur, opts) do
        {:ok, html} -> {:ok, html}
        {:error, reason} -> {:error, {:web_ui_error, reason}}
        other -> {:error, {:unexpected_response, other}}
      end
    rescue
      error -> {:error, {:web_ui_exception, error}}
    end
  end

  # Fallback renderer when WebUI is not available
  defp render_fallback(canonical_iur, opts) do
    html = generate_html(canonical_iur, opts)
    {:ok, html}
  end

  # Generate static HTML from canonical IUR
  defp generate_html(%{"type" => "screen"} = iur, opts) do
    seo_enabled = Keyword.get(opts, :seo_enabled, true)
    elm_enabled = Keyword.get(opts, :elm_enabled, false)
    elm_module = Keyword.get(opts, :elm_module, "Main")

    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      #{if seo_enabled, do: generate_seo_tags(iur), else: ""}
      #{if elm_enabled, do: generate_elm_script(elm_module), else: ""}
    </head>
    <body class="ash-screen ash-screen-#{iur["name"]}" data-screen-id="#{iur["id"]}">
      #{generate_children(iur["children"])}
      #{if elm_enabled, do: generate_elm_mount(), else: ""}
    </body>
    </html>
    """
  end

  defp generate_html(%{"type" => type, "id" => id} = iur, _opts) do
    """
    <div class="ash-widget ash-widget-#{type}" data-widget-id="#{id}">
      #{generate_children(iur["children"])}
    </div>
    """
  end

  defp generate_seo_tags(iur) do
    """
    <title>#{iur["name"] || "AshUI Screen"}</title>
    <meta name="description" content="Generated by AshUI">
    """
  end

  defp generate_elm_script(module) do
    """
    <script src="/assets/#{String.downcase(module)}.js"></script>
    """
  end

  defp generate_elm_mount do
    """
    <div id="elm-app"></div>
    <script>
      Elm.Main.init({ node: document.getElementById("elm-app") });
    </script>
    """
  end

  defp generate_children(nil), do: ""
  defp generate_children([]), do: ""
  defp generate_children(children) when is_list(children) do
    Enum.map_join(children, &generate_html(&1, []))
  end
end
