defmodule AshUI.Rendering.WebUIAdapterTest do
  use ExUnit.Case, async: true

  alias AshUI.Rendering.WebUIAdapter
  alias AshUI.Compilation.IUR

  describe "Section 7.3.1 - WebUI Renderer Adapter" do
    test "render/2 returns HTML for screen IUR" do
      canonical_iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test_screen",
        "layout" => "column",
        "children" => [
          %{"type" => "text", "id" => "text-1", "props" => %{"content" => "Hello"}, "children" => [], "metadata" => %{}}
        ],
        "bindings" => [],
        "metadata" => %{}
      }

      assert {:ok, html} = WebUIAdapter.render(canonical_iur)
      assert is_binary(html)
      assert String.contains?(html, "<!DOCTYPE html>")
      assert String.contains?(html, "ash-screen")
      assert String.contains?(html, "test_screen")
    end

    test "render/2 accepts options" do
      canonical_iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test_screen",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      assert {:ok, html} = WebUIAdapter.render(canonical_iur, seo_enabled: false)
      assert is_binary(html)
      assert String.contains?(html, "ash-screen")
    end

    test "available?/0 returns boolean" do
      result = WebUIAdapter.available?()
      assert is_boolean(result)
    end

    test "render_ash_iur/2 converts and renders Ash IUR" do
      ash_iur = struct(IUR,
        id: "test-id",
        type: :screen,
        name: "test_screen",
        attributes: %{"layout" => :row},
        children: [],
        bindings: [],
        metadata: %{},
        version: 1
      )

      assert {:ok, html} = WebUIAdapter.render_ash_iur(ash_iur)
      assert is_binary(html)
      assert String.contains?(html, "<!DOCTYPE html>")
      assert String.contains?(html, "ash-screen")
    end
  end

  describe "Section 7.3.2 - WebUI-specific Features" do
    setup do
      {:ok, canonical_iur: %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "user_profile",
        "layout" => "column",
        "children" => [
          %{
            "type" => "text",
            "id" => "text-1",
            "props" => %{"content" => "Welcome", "size" => 24},
            "children" => [],
            "metadata" => %{}
          }
        ],
        "bindings" => [
          %{
            "id" => "binding-1",
            "type" => "bidirectional",
            "target" => "username",
            "source" => %{"resource" => "User", "field" => "name", "default" => "Guest"},
            "element_id" => "input-1",
            "metadata" => %{}
          }
        ],
        "metadata" => %{"keywords" => ["profile", "user"]}
      }}
    end

    test "configure_seo/2 generates SEO configuration", %{canonical_iur: iur} do
      seo_config = WebUIAdapter.configure_seo(iur)

      assert seo_config.enabled == true
      assert seo_config.title == "user_profile"
      assert seo_config.description =~ "Generated by AshUI"
      assert is_list(seo_config.keywords)
      assert "profile" in seo_config.keywords
      assert "User" in seo_config.keywords
    end

    test "configure_seo/2 respects custom title and description", %{canonical_iur: iur} do
      seo_config = WebUIAdapter.configure_seo(iur,
        title: "Custom Title",
        description: "Custom description"
      )

      assert seo_config.title == "Custom Title"
      assert seo_config.description == "Custom description"
    end

    test "configure_seo/2 can be disabled", %{canonical_iur: iur} do
      seo_config = WebUIAdapter.configure_seo(iur, seo_enabled: false)

      assert seo_config.enabled == false
    end

    test "configure_seo/2 generates OG tags", %{canonical_iur: iur} do
      seo_config = WebUIAdapter.configure_seo(iur)

      assert is_map(seo_config.og_tags)
      title = Map.get(seo_config.og_tags, "title") || Map.get(seo_config.og_tags, :title)
      type = Map.get(seo_config.og_tags, "type") || Map.get(seo_config.og_tags, :type)
      assert title == "user_profile"
      assert type == "website"
    end

    test "configure_seo/2 generates Twitter tags", %{canonical_iur: iur} do
      seo_config = WebUIAdapter.configure_seo(iur)

      assert is_map(seo_config.twitter_tags)
      # Check if keys are strings or atoms
      card_value = Map.get(seo_config.twitter_tags, "card") || Map.get(seo_config.twitter_tags, :card)
      title_value = Map.get(seo_config.twitter_tags, "title") || Map.get(seo_config.twitter_tags, :title)
      assert card_value == "summary"
      assert title_value == "user_profile"
    end

    test "configure_elm_integration/2 generates Elm configuration", %{canonical_iur: iur} do
      elm_config = WebUIAdapter.configure_elm_integration(iur,
        elm_enabled: true,
        elm_module: "App")

      assert elm_config.enabled == true
      assert elm_config.module == "App"
      assert elm_config.js_file == "app.js"
      assert elm_config.mount_node == "elm-app"
    end

    test "configure_elm_integration/2 extracts ports from bindings", %{canonical_iur: iur} do
      elm_config = WebUIAdapter.configure_elm_integration(iur, elm_enabled: true)

      assert is_map(elm_config.ports)
      assert Map.has_key?(elm_config.ports, "username")
    end

    test "configure_elm_integration/2 respects elm_enabled option", %{canonical_iur: iur} do
      elm_config = WebUIAdapter.configure_elm_integration(iur, elm_enabled: false)

      assert elm_config.enabled == false
    end

    test "configure_assets/2 generates asset configuration", %{canonical_iur: iur} do
      asset_config = WebUIAdapter.configure_assets(iur)

      assert asset_config.base_url == "/assets"
      assert is_list(asset_config.css_files)
      assert is_list(asset_config.js_files)
      assert asset_config.fingerprinted == true
    end

    test "configure_assets/2 respects custom assets_url", %{canonical_iur: iur} do
      asset_config = WebUIAdapter.configure_assets(iur, assets_url: "/static")

      assert asset_config.base_url == "/static"
    end

    test "configure_assets/2 can disable CSS and JS", %{canonical_iur: iur} do
      asset_config = WebUIAdapter.configure_assets(iur,
        include_css: false,
        include_js: false)

      assert asset_config.css_files == []
      assert asset_config.js_files == []
    end

    test "configure_ssg/2 generates SSG configuration", %{canonical_iur: iur} do
      ssg_config = WebUIAdapter.configure_ssg(iur)

      assert ssg_config.output_path == "output"
      assert ssg_config.generate_index == true
      assert ssg_config.prerender == false
      assert ssg_config.incremental == false
    end

    test "configure_ssg/2 respects custom options", %{canonical_iur: iur} do
      ssg_config = WebUIAdapter.configure_ssg(iur,
        output_path: "dist",
        prerender: true,
        incremental_ssg: true)

      assert ssg_config.output_path == "dist"
      assert ssg_config.prerender == true
      assert ssg_config.incremental == true
    end
  end

  describe "Section 7.3.1 - HTML Generation" do
    test "generates complete HTML document" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur)
      assert String.contains?(html, "<!DOCTYPE html>")
      assert String.contains?(html, "<html")
      assert String.contains?(html, "<head>")
      assert String.contains?(html, "<body ")
      assert String.contains?(html, "</html>")
    end

    test "includes SEO meta tags when enabled" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "My Page",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, seo_enabled: true)
      assert String.contains?(html, "<title>My Page</title>")
      assert String.contains?(html, "name=\"description\"")
    end

    test "excludes SEO meta tags when disabled" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, seo_enabled: false)
      refute String.contains?(html, "<title>")
    end

    test "includes Elm script when enabled" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, elm_enabled: true, elm_module: "Main")
      assert String.contains?(html, "main.js")
      assert String.contains?(html, "elm-app")
      assert String.contains?(html, "Elm.Main.init")
    end

    test "includes Elm ports when bindings present" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [
          %{
            "id" => "binding-1",
            "type" => "bidirectional",
            "target" => "username",
            "source" => %{"default" => "Guest"},
            "element_id" => "input-1",
            "metadata" => %{}
          }
        ],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, elm_enabled: true)
      assert String.contains?(html, "flags:")
    end

    test "includes asset tags when enabled" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, include_css: true, include_js: true)
      assert String.contains?(html, "app.css")
      assert String.contains?(html, "app.js")
    end

    test "respects custom assets_url" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "test",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur, assets_url: "/static")
      assert String.contains?(html, "/static/app.css")
    end

    test "generates widget elements with data attributes" do
      iur = %{
        "type" => "text",
        "id" => "widget-1",
        "props" => %{},
        "children" => [],
        "metadata" => %{}
      }

      {:ok, html} = WebUIAdapter.render(iur)
      assert String.contains?(html, "ash-widget")
      assert String.contains?(html, "data-widget-id=\"widget-1\"")
    end
  end

  describe "Section 7.3.2 - Keyword Extraction" do
    test "extracts keywords from metadata" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "product_page",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{"keywords" => ["shop", "ecommerce"]}
      }

      seo_config = WebUIAdapter.configure_seo(iur)
      assert "shop" in seo_config.keywords
      assert "ecommerce" in seo_config.keywords
    end

    test "generates keywords from screen name" do
      iur = %{
        "type" => "screen",
        "id" => "screen-1",
        "name" => "user_dashboard",
        "layout" => "column",
        "children" => [],
        "bindings" => [],
        "metadata" => %{}
      }

      seo_config = WebUIAdapter.configure_seo(iur)
      assert "User" in seo_config.keywords
      assert "Dashboard" in seo_config.keywords
    end
  end
end
